logging.level:
  root: INFO

management:
  endpoint:
    health:
      show-details: always
      
server:
  port: 8085
  servlet:
    context-path: /exchange-rates
    
spring.jackson.time-zone: America/Lima
spring.jackson.locale: es_PE

spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
  datasource:
    url: jdbc:sqlserver://HPENVY-ANDREI\SQL2019;databaseName=exchangerate
    username: sa
    password: Theo@ndre
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    baseline-on-migrate: true
    enabled: true
  sql:
    init:
      platform: sqlserver
      
identity-provider:
  url-introspect: https://api.bcp.com/identity/introspect
  resource-id: ms-bcp-exchange-rate
  resource-secret: 609DED5D-09E7-4282-96F4-14DD3B6CF6C9
  url-identity: https://api.bcp.com/identity
  client-id: bcp.swagger
  client-secret: 71D58FDC-8467-4D61-9010-DCE401F16A78

disable-security: true      
      