logging.level:
  root: INFO

management:
  endpoint:
    health:
      show-details: always
      
server:
  port: 8085
  servlet:
    context-path: /exchange-rates
    
spring.jackson.time-zone: America/Lima
spring.jackson.locale: es_PE

spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
  datasource:
    url: jdbc:sqlserver://HPENVY-ANDREI\SQL2019;databaseName=exchangerate
    username: sa
    password: Theo@ndre
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
    baseline-on-migrate: true
    enabled: true
  sql:
    init:
      platform: sqlserver
      